[workspace]
resolver = "2"
members = [
    "ohms-adaptq",
    "ohms-agent",
    "ohms-coordinator",
    "ohms-econ",
    "ohms-model"
]

[workspace.dependencies]
ic-cdk = "0.15"
ic-cdk-macros = "0.15"
candid = "0.10"
serde = { version = "1.0", features = ["derive"] }
ic-stable-structures = "0.6"
